### ISSUE TITLE
Broken postman collection link

### ISSUE THREAD

**Issue by alexlyzhov** [aimonlabs/aimon-python-sdk#39]
"Step 2: Download the Postman Collection specified below to access the API" - the https://github.com/aimonlabs/aimon-python-sdk/blob/alex_readme_changes/examples/postman_collections link is broken and it's unclear what it refers to

**Comment by pjoshi30** [comment]
This is a relic from the first version of the API that we published Postman docs for. We should get rid of this section entirely. I will send a PR.
